### ISSUE TITLE
icon position in jquery mobile 1.3

### ISSUE THREAD

**Issue by leopittoni** [commadelimited/jQuery-Mobile-Icon-Pack#30] opened 2013-01-15 18:21 UTC
Hi!
In jquery mobile 1.3 the normal icons of jquery mobile are shifted to the top, if I include the new css file...

**Comment by commadelimited** [comment] 2013-02-06 02:44
Do you have an example? I spent a good amount of time making sure the position of the icons was correct. Can you provide a little more information such as browser and browser version? A screenshot might also help.

**Comment by sibartlett** [comment] 2013-02-11 00:21
I can confirm that the alignment of all the normal icons is not correct when using jQuery Mobile 1.3, and I tested using Chrome and Firefox.

**Comment by sibartlett** [comment] 2013-02-11 00:26
Looks like this icon pack needs to be updated - there are two new icons in jQuery Mobile 1.3.

**Comment by commadelimited** [comment] 2013-02-12 04:49
Yep. Looks like an edit icon and a "list" icon, ala Facebook style side nav.

http://jquerymobile.com/demos/1.3.0-rc.1/css/themes/default/images/icons-36-black.png

**Comment by stevevance** [comment] 2013-03-22 06:17
Screenshot of the issue.
![Screen Shot 2013-03-22 at 01 16 42 ](https://f.cloud.github.com/assets/1330459/289591/197f4f52-92b8-11e2-921a-2d3ef7566fbe.png)

**Comment by stevevance** [comment] 2013-03-31 22:52
You can see the code here: http://bikechi.com/map.html

**Comment by commadelimited** [comment] 2013-04-01 04:30
Just pushed the fix for this.

**Closed as completed by commadelimited** 2013-04-01 04:30 UTC
